# Generated by Django 2.1.3 on 2018-12-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_module', '0002_quran2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quran2',
        ),
    ]
